### ISSUE TITLE
add simple example of workflow

### ISSUE THREAD

**Issue by rgreminger** [tilburgsciencehub/deprecated-website#17]
For my own setup, I created a basic workflow and put this together in a repository.
https://github.com/rgreminger/example-make-workflow

Since it's pretty simple and based on the example directory structure, it could provide a starting point for people to build their own projects. However, at this point, the makefile will only work in Windows. If this is not an issue, this could be referenced to in the examples section.

**Comment by hannesdatta** [comment]
sweet - I'll add it in one of the next builds!!! Thanks so much!!!

@hulaizh, can you please fork Rafael's work, and do a code audit + fix the makefile to run on Mac? Issue a PR with your changes to Rafael when you're done (to see how to contribute to an open source project, see our own contribution guidelines/tips at https://github.com/hannesdatta/tilburg-science-hub/blob/tilburg-update/CONTRIBUTING.md).

**Comment by hannesdatta** [comment]
@rgreminger: added it to our examples, page should be live in a bit! Thanks again, Rafael.

@hulaizh will ensure portability for Macs.

**Comment by hannesdatta** [comment]
Hi @hulaizh, any update on this?

**Comment by hulaizh** [comment]
Works on Mac!
